/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle.test.publication;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
